services:
  app:
    build:
      context: .
    image: volteecbackend:dev

  migrate:
    build:
      context: .
    image: volteecbackend:dev

  revert:
    build:
      context: .
    image: volteecbackend:dev
